- src/main/java/com/onaio/steps/handler/actions/ImportHandler.java
Adds the surveyId to the import URL in the format:
```
[base url]/[device id]/[survey id]
```
Fixes issue #56
> SurveyId in Import URL

- src/main/java/com/onaio/steps/activities/SettingsActivity.java
- src/main/java/com/onaio/steps/handler/actions/ImportHandler.java
- src/main/java/com/onaio/steps/orchestrators/flows/ParticipantFlow.java
- src/main/res/layout/settings.xml
- src/main/res/menu/main_activity_actions.xml
Move the import button to the settings activity under the "Household"
app type
> Import Button in Settings Activity

- src/main/java/com/onaio/steps/Properties.java
- src/main/java/com/onaio/steps/exceptions/NoUniqueIdException.java
- src/main/java/com/onaio/steps/handler/actions/ExportHandler.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/helper/Device.java
- src/test/java/com/onaio/steps/handler/actions/ExportHandlerTest.java
Adds the 'Date Added' field to the exported CSV with the date format 'yyyy/MM/dd'. Also contains changes from pull request #49 
Fixes issue #33
> Household Registration Date in Export

- src/main/java/com/onaio/steps/Properties.java
- src/main/java/com/onaio/steps/activities/SettingsActivity.java
- src/main/java/com/onaio/steps/helper/AuthDialog.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/helper/DatabaseHelper.java
- src/main/java/com/onaio/steps/orchestrators/FlowOrchestrator.java
- src/main/res/layout/dialog_auth.xml
- src/main/res/layout/settings.xml
- src/main/res/values/strings.xml
- src/test/java/com/onaio/steps/activities/SettingsActivityTest.java
- src/test/java/com/onaio/steps/helper/AuthDialogTest.java
Makes the settings screen password protected and adds a 'Wipe Data' button at the bottom of the settings screen
Fix for issue #35
> Settings Password And Data Wipe

- src/main/res/layout/main.xml
Make the 'Add New Household' and 'Submit Data' buttons in the Main
Activity the same variable height
Fix for issue #66
> Matching Main Activity Button Heights

- src/main/java/com/onaio/steps/activities/NewHouseholdActivity.java
- src/main/java/com/onaio/steps/handler/actions/ExportHandler.java
- src/main/java/com/onaio/steps/handler/actions/ImportHandler.java
- src/main/java/com/onaio/steps/helper/CursorHelper.java
- src/main/java/com/onaio/steps/model/Household.java
- src/main/java/com/onaio/steps/modelViewWrapper/HouseholdViewWrapper.java
- src/test/java/com/onaio/steps/activities/EditHouseholdActivityTest.java
- src/test/java/com/onaio/steps/activities/EditMemberActivityTest.java
- src/test/java/com/onaio/steps/activities/HouseholdListActivityTest.java
- src/test/java/com/onaio/steps/activities/NewHouseholdActivityTest.java
- src/test/java/com/onaio/steps/activities/NewMemberActivityTest.java
- src/test/java/com/onaio/steps/activities/SettingsActivityTest.java
- src/test/java/com/onaio/steps/handler/actions/DeleteMemberHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/EditMemberActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/HouseholdActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/MemberActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/NewHouseholdActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/factories/HouseholdActivityFactoryTest.java
- src/test/java/com/onaio/steps/handler/factories/MemberActivityFactoryTest.java
- src/test/java/com/onaio/steps/model/HouseholdTest.java
- src/test/java/com/onaio/steps/model/MemberTest.java
- src/test/java/com/onaio/steps/model/ReElectReasonTest.java
- src/test/java/com/onaio/steps/modelViewWrapper/HouseholdViewWrapperTest.java
- src/test/java/com/onaio/steps/modelViewWrapper/MemberViewWrapperTest.java
Makes the unique device id set for a household immutable
Fix for issue #69
> Immutable Unique Device ID

- src/main/java/com/onaio/steps/Properties.java
Update the default URLs in the settings screen to point to the STEPS v2
site
Fix for issue #77
> STEPSv2 URLS

- src/main/java/com/onaio/steps/handler/actions/ExportHandler.java
- src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java
- src/main/java/com/onaio/steps/helper/UploadFileTask.java
Show a dialog showing whether the data transfer after export was
successful
Fix for issue #81
> Data Transfer Status Dialog

- src/main/res/layout/dialog_submit_data.xml
- src/test/java/com/onaio/steps/handler/actions/SubmitDataHandlerTest.java
Make the checkboxes in the submit data dialog checked by default
Fix for issue #79
> Submit Data Dialog Checkboxes

- src/main/java/com/onaio/steps/helper/AuthDialog.java
- src/main/res/layout/dialog_auth.xml
- src/test/java/com/onaio/steps/helper/AuthDialogTest.java
Make the settings password visible by default
Fix for issue #86
> Default Visible Settings Password

- src/main/res/values-ar/strings.xml
Update Arabic translations for strings requested for in issue #85
Fix for issue #85
> Arabic Translations

- build.gradle
- src/main/java/com/onaio/steps/Properties.java
Remove the import and export URLs in preparation for publishing the app on the Playstore
Fix for issue #41
> Playstore publish

- src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java
- src/main/java/com/onaio/steps/handler/factories/ParticipantListActivityFactory.java
- src/test/java/com/onaio/steps/handler/factories/ParticipantListActivityFactoryTest.java
Make the 'Send Data' button immediately go to ODK Collect when clicked
while in participant mode
Fix for issue #95
> 'Send Data' Button in Participant Mode

- src/main/java/com/onaio/steps/handler/actions/ImportHandler.java
- src/main/java/com/onaio/steps/helper/UploadFileTask.java
- src/main/java/com/onaio/steps/orchestrators/flows/HouseholdFlow.java
Make the import and export URL settings not mandatory
Fix for issue #94
> Non-mandatory Import & Export URL Settings

- src/main/java/com/onaio/steps/modelViewWrapper/HouseholdViewWrapper.java
- src/main/java/com/onaio/steps/modelViewWrapper/ParticipantViewWrapper.java
- src/test/java/com/onaio/steps/activities/EditParticipantActivityTest.java
- src/test/java/com/onaio/steps/activities/NewMemberActivityTest.java
- src/test/java/com/onaio/steps/activities/NewParticipantActivityTest.java
- src/test/java/com/onaio/steps/activities/ParticipantActivityTest.java
- src/test/java/com/onaio/steps/activities/ParticipantListActivityTest.java
- src/test/java/com/onaio/steps/handler/actions/ExportHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/HouseholdActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/MemberActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/NewParticipantActivityHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/ParticipantActivityHandlerTest.java
- src/test/java/com/onaio/steps/model/HouseholdTest.java
- src/test/java/com/onaio/steps/model/MemberTest.java
- src/test/java/com/onaio/steps/model/ODKForm/strategy/ParticipantFormStrategyTest.java
- src/test/java/com/onaio/steps/model/ParticipantTest.java
- src/test/java/com/onaio/steps/model/ReElectReasonTest.java
- src/test/java/com/onaio/steps/modelViewWrapper/HouseholdViewWrapperTest.java
- src/test/java/com/onaio/steps/modelViewWrapper/MemberViewWrapperTest.java
- src/test/java/com/onaio/steps/modelViewWrapper/ParticipantViewWrapperTest.java
Ensure all dates generated in the app are in the English locale
Fix for issue #96
> English Dates

- src/main/java/com/onaio/steps/orchestrators/flows/HouseholdFlow.java
- src/main/java/com/onaio/steps/orchestrators/flows/ParticipantFlow.java
- src/test/java/com/onaio/steps/orchestrators/flows/HouseholdFlowTest.java
- src/test/java/com/onaio/steps/orchestrators/flows/ParticipantFlowTest.java
Ensure fields in the settings activity are trimmed before saving
Fix for issue #100
> Trimmed Settings

- src/main/java/com/onaio/steps/adapters/HouseholdAdapter.java
- src/main/java/com/onaio/steps/helper/CursorHelper.java
- src/main/java/com/onaio/steps/model/Household.java
- src/main/java/com/onaio/steps/model/Member.java
Hi @ekigamba could you look this PR
> Add name of participant

- src/main/java/com/onaio/steps/activities/BaseListActivity.java
- src/main/java/com/onaio/steps/activities/HouseholdListActivity.java
- src/main/java/com/onaio/steps/activities/ParticipantActivity.java
- src/main/java/com/onaio/steps/activities/ParticipantListActivity.java
- src/main/java/com/onaio/steps/adapters/HouseholdAdapter.java
- src/main/java/com/onaio/steps/adapters/MemberAdapter.java
- src/main/java/com/onaio/steps/adapters/ParticipantAdapter.java
- src/main/java/com/onaio/steps/handler/actions/FinalisedFormHandler.java
- src/main/java/com/onaio/steps/handler/activities/DataSubmissionResultHandler.java
- src/main/java/com/onaio/steps/handler/factories/HouseholdListActivityFactory.java
- src/main/java/com/onaio/steps/handler/factories/ParticipantListActivityFactory.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/model/Household.java
- src/main/java/com/onaio/steps/model/InterviewStatus.java
- src/main/java/com/onaio/steps/model/ODKForm/ODKSavedForm.java
- src/main/java/com/onaio/steps/model/Participant.java
- src/main/java/com/onaio/steps/model/RequestCode.java
- src/main/res/values/strings.xml
- src/test/java/com/onaio/steps/activities/HouseholdListActivityTest.java
- src/test/java/com/onaio/steps/handler/actions/FinalisedFormHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/DataSubmissionResultHandlerTest.java
- src/test/java/com/onaio/steps/handler/factories/HouseholdListActivityFactoryTest.java
- src/test/java/com/onaio/steps/handler/factories/ParticipantListActivityFactoryTest.java
Hi @ekigamba could you review this. Issue # [17](https://github.com/onaio/WHOSteps/issues/17)
> Update steps app to communicating with ODK App when the data sent to the server

- src/main/AndroidManifest.xml
- src/main/java/com/onaio/steps/external/DataKeys.java
- src/main/java/com/onaio/steps/external/DataProviderActivity.java
- src/main/java/com/onaio/steps/handler/strategies/survey/TakeSurveyForHouseholdStrategy.java
- src/main/java/com/onaio/steps/handler/strategies/survey/TakeSurveyForParticipantStrategy.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/model/ODKForm/ODKForm.java
- src/main/java/com/onaio/steps/model/ODKForm/strategy/HouseholdMemberFormStrategy.java
- src/main/java/com/onaio/steps/model/ODKForm/strategy/ParticipantFormStrategy.java
- src/main/java/com/onaio/steps/model/ODKForm/strategy/interfaces/IFormStrategy.java
- src/main/res/values/customtheme.xml
- src/main/res/values/strings.xml
- src/test/java/com/onaio/steps/external/DataProviderActivityTest.java
- src/test/java/com/onaio/steps/model/ODKForm/ODKFormTest.java
- src/test/java/com/onaio/steps/model/ODKForm/strategy/HouseholdMemberFormStrategyTest.java
- src/test/java/com/onaio/steps/model/ODKForm/strategy/ParticipantFormStrategyTest.java
> Preload data in the ODK form

- src/main/java/com/onaio/steps/activities/SettingsActivity.java
- src/main/java/com/onaio/steps/model/ODKForm/ODKBlankForm.java
- src/main/res/layout/settings.xml
- src/test/java/com/onaio/steps/activities/SettingsActivityTest.java
> Enhance the Form-Id field in the Steps Setting Screen

- src/main/java/com/onaio/steps/handler/ExceptionHandler.java
- src/main/java/com/onaio/steps/handler/actions/TakeSurveyHandler.java
- src/main/java/com/onaio/steps/handler/strategies/survey/TakeSurveyForHouseholdStrategy.java
- src/main/java/com/onaio/steps/handler/strategies/survey/TakeSurveyForParticipantStrategy.java
- src/main/java/com/onaio/steps/handler/strategies/survey/interfaces/ITakeSurveyStrategy.java
- src/main/res/values/strings.xml
- src/test/java/com/onaio/steps/handler/ExceptionHandlerTest.java
> Error message when Interview now is selected

- src/main/java/com/onaio/steps/helper/UploadFileTask.java
- src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java
> App crash on Uploading Data

- src/main/java/com/onaio/steps/helper/DatabaseHelper.java
- src/test/java/com/onaio/steps/helper/DatabaseHelperTest.java
> DatabaseHelper.java line 55 com.onaio.steps.helper.DatabaseHelper.onUpgrade

- src/main/java/com/onaio/steps/handler/strategies/survey/TakeSurveyForHouseholdStrategy.java
> Signaling data transfer to the cloud

- src/main/AndroidManifest.xml
- src/main/java/com/onaio/steps/handler/actions/SubmitDataHandler.java
- src/test/java/com/onaio/steps/handler/actions/SubmitDataHandlerTest.java
> App Crash in SubmitDataHandler

- src/main/java/com/onaio/steps/clients/HouseholdService.java
- src/main/java/com/onaio/steps/handler/actions/ExportHandler.java
- src/main/java/com/onaio/steps/handler/actions/ImportHandler.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/helper/UploadFileTask.java
- src/main/java/com/onaio/steps/orchestrators/flows/HouseholdFlow.java
- src/main/java/com/onaio/steps/utils/QRCodeUtils.java
- src/main/res/layout/settings.xml
- src/main/res/values-ar/strings.xml
- src/main/res/values-es/strings.xml
- src/main/res/values-fr/strings.xml
- src/main/res/values-ru/strings.xml
- src/main/res/values/strings.xml
- src/test/java/com/onaio/steps/handler/actions/ImportHandlerTest.java
- src/test/java/com/onaio/steps/handler/activities/HouseholdActivityMenuItemHandlerTest.java
- src/test/java/com/onaio/steps/orchestrators/flows/HouseholdFlowTest.java
- src/test/java/com/onaio/steps/utils/QRCodeUtilsTest.java
> Remove survey ID from the apk

- src/main/AndroidManifest.xml
- src/main/java/com/onaio/steps/handler/actions/ShareHandler.java
- src/main/java/com/onaio/steps/helper/Constants.java
- src/main/java/com/onaio/steps/utils/QRCodeUtils.java
- src/main/res/xml/file_provider_paths.xml
- src/test/java/com/onaio/steps/handler/actions/ShareHandlerTest.java
> App Crash on Share QR Code

- build.gradle
> Enable Code Obfuscation in Release Build

- src/main/AndroidManifest.xml
- src/main/res/xml/backup_rules.xml
> Disable auto backup

- build.gradle
- src/main/AndroidManifest.xml
- src/main/java/com/onaio/steps/StepsApplication.java
- src/main/java/com/onaio/steps/dialogs/HouseholdUploadResultDialog.java
- src/main/java/com/onaio/steps/helper/UploadFileTask.java
- src/main/java/com/onaio/steps/model/UploadResult.java
- src/main/java/com/onaio/steps/utils/CrashlyticsTree.java
- src/main/res/layout/item_household_upload_result.xml
- src/test/java/com/onaio/steps/helper/UploadFileTaskTest.java
- src/test/java/com/onaio/steps/utils/CrashlyticsTreeTest.java
> Show a specific error when upload failed

- src/main/java/com/onaio/steps/activities/BackupLocationActivity.java
- src/main/java/com/onaio/steps/activities/SettingsImportExportActivity.java
- src/main/java/com/onaio/steps/handler/actions/PickImageHandler.java
- src/main/java/com/onaio/steps/handler/actions/QRCodeScanHandler.java
- src/main/java/com/onaio/steps/handler/actions/SaveToSDCardHandler.java
- src/main/java/com/onaio/steps/handler/exceptions/ExceptionHandler.java
- src/main/java/com/onaio/steps/helper/Device.java
- src/main/java/com/onaio/steps/helper/FileUtil.java
- src/main/java/com/onaio/steps/helper/RegisterUniqueDeviceIdTask.java
- src/main/java/com/onaio/steps/tasks/GenerateQRCodeAsyncTask.java
- src/main/java/com/onaio/steps/tasks/SaveQRCodeAsyncTask.java
- src/main/java/com/onaio/steps/utils/CompressionUtils.java
- src/main/java/com/onaio/steps/utils/QRCodeUtils.java
> Ensure the app does not log sensitive information

- build.gradle
> Investigate the Bootstrap Activity

- src/main/java/com/onaio/steps/helper/DatabaseHelper.java
- src/test/java/com/onaio/steps/helper/DatabaseHelperTest.java
> App uses SQLite database and executes raw SQL query

- src/main/java/com/onaio/steps/helper/AuthDialog.java
- src/main/java/com/onaio/steps/helper/HashGenerator.java
- src/main/java/com/onaio/steps/utils/QRCodeUtils.java
- src/test/java/com/onaio/steps/helper/AuthDialogTest.java
- src/test/java/com/onaio/steps/helper/HashGeneratorTest.java
> Replace MD5 with SHA-256

- build.gradle
Closes #201 
- Include v1 scheme signing for maximum compatibilty
- Bump up version 🔖
> Enable v1 Jar signing

- build.gradle
- src/main/java/com/onaio/steps/handler/exceptions/ExceptionHandler.java
Update STEPs version to v3.1.2
> Log unhandled errors
